// Synthetic dataset modeling a subsea cable business: a handful of projects
// that intentionally *share* the same vessels, factories, warehouse and
// storage barge, so the resulting graph demonstrates real cross-project
// asset dependencies rather than isolated trees.

export const assets = [
  {
    name: 'MV Nexus Installer',
    assetType: 'Cable-Lay Vessel',
    owner: 'Nexus Marine Ltd.',
    location: 'Rotterdam, NL',
    capacity: '6,000t cable carousel',
    status: 'In Use',
    dayRateUsd: 185000,
  },
  {
    name: 'MV Atlantic Surveyor',
    assetType: 'Survey Vessel',
    owner: 'OceanScan Surveys',
    location: 'Aberdeen, UK',
    capacity: 'Multibeam sonar + AUV bay',
    status: 'Available',
    dayRateUsd: 62000,
  },
  {
    name: 'ROV Deep Explorer',
    assetType: 'ROV Support Vessel',
    owner: 'SubTech Marine',
    location: 'Bergen, NO',
    capacity: '3,000m depth rated',
    status: 'In Use',
    dayRateUsd: 78000,
  },
  {
    name: 'Storage Barge Delta-7',
    assetType: 'Storage Barge',
    owner: 'Delta Marine Logistics',
    location: 'Emden, DE',
    capacity: '4,500t deck load',
    status: 'Available',
    dayRateUsd: 21000,
  },
  {
    name: 'Trenchmaster Burial Vessel',
    assetType: 'Burial Vessel',
    owner: 'SeaTrench Services',
    location: 'Esbjerg, DK',
    capacity: '1.5m burial depth plough',
    status: 'Maintenance',
    dayRateUsd: 95000,
  },
  {
    name: 'Rotterdam Cable Manufacturing Plant',
    assetType: 'Manufacturing Plant',
    owner: 'EuroCable Industries',
    location: 'Rotterdam, NL',
    capacity: '120,000t annual output',
    status: 'In Use',
  },
  {
    name: 'Singapore Cable Factory',
    assetType: 'Manufacturing Plant',
    owner: 'EuroCable Industries',
    location: 'Jurong, SG',
    capacity: '80,000t annual output',
    status: 'In Use',
  },
  {
    name: 'North Sea Logistics Warehouse',
    assetType: 'Warehouse',
    owner: 'Delta Marine Logistics',
    location: 'Esbjerg, DK',
    capacity: '15,000 sqm covered storage',
    status: 'Available',
  },
];

export const projects = [
  {
    name: 'Baltic Wind Connector',
    client: 'Baltic Grid Holdings',
    region: 'Baltic Sea',
    status: 'Active',
    startDate: '2024-03-01',
    endDate: '2026-11-30',
    budgetUsd: 420000000,
    projectManager: 'Elena Kowalski',
  },
  {
    name: 'NorthLink HVDC Interconnector',
    client: 'NorthLink Energy Transmission',
    region: 'North Sea',
    status: 'Active',
    startDate: '2023-06-15',
    endDate: '2026-05-31',
    budgetUsd: 950000000,
    projectManager: 'Rajesh Mehta',
  },
  {
    name: 'Emerald Isle Telecom Backbone',
    client: 'Emerald Connect Telecom',
    region: 'Irish Sea',
    status: 'Planning',
    startDate: '2025-01-10',
    endDate: '2027-02-28',
    budgetUsd: 180000000,
    projectManager: "Siobhan O'Brien",
  },
  {
    name: 'Gulf Stream Power Bridge',
    client: 'Atlantic Power Partners',
    region: 'North Atlantic',
    status: 'On Hold',
    startDate: '2022-09-01',
    endDate: '2025-12-31',
    budgetUsd: 1200000000,
    projectManager: 'Marcus Alden',
  },
  {
    name: 'Coral Sea Renewable Export Cable',
    client: 'Pacific Renewables Group',
    region: 'Coral Sea',
    status: 'Completed',
    startDate: '2021-04-01',
    endDate: '2024-06-30',
    budgetUsd: 610000000,
    projectManager: 'Amara Chen',
  },
];

export const cables = [
  {
    name: 'Baltic-1 HVDC Cable',
    cableType: 'HVDC',
    voltageKv: 525,
    lengthKm: 180,
    manufacturer: 'EuroCable Industries',
    status: 'Installed',
  },
  {
    name: 'Baltic-2 HVDC Cable',
    cableType: 'HVDC',
    voltageKv: 525,
    lengthKm: 175,
    manufacturer: 'EuroCable Industries',
    status: 'Manufacturing',
  },
  {
    name: 'NorthLink Interconnector Cable A',
    cableType: 'HVDC',
    voltageKv: 640,
    lengthKm: 410,
    manufacturer: 'EuroCable Industries',
    status: 'Installed',
  },
  {
    name: 'NorthLink Interconnector Cable B',
    cableType: 'HVDC',
    voltageKv: 640,
    lengthKm: 405,
    manufacturer: 'Singapore Cable Factory',
    status: 'Shipped',
  },
  {
    name: 'Emerald Backbone Fiber Trunk',
    cableType: 'Fiber Optic Telecom',
    lengthKm: 260,
    manufacturer: 'Singapore Cable Factory',
    status: 'Design',
  },
  {
    name: 'Gulf Stream HVDC Main Cable',
    cableType: 'HVDC',
    voltageKv: 320,
    lengthKm: 890,
    manufacturer: 'EuroCable Industries',
    status: 'Manufacturing',
  },
  {
    name: 'Coral Sea Export Cable',
    cableType: 'HVAC',
    voltageKv: 275,
    lengthKm: 140,
    manufacturer: 'Singapore Cable Factory',
    status: 'Commissioned',
  },
];

export const campaigns = [
  {
    name: 'Baltic Route Survey 2024',
    campaignType: 'Route Survey',
    startDate: '2024-04-01',
    endDate: '2024-06-15',
    status: 'Completed',
    location: 'Baltic Sea corridor',
  },
  {
    name: 'Baltic-1 Cable Installation',
    campaignType: 'Cable Installation',
    startDate: '2025-05-01',
    endDate: '2025-08-20',
    status: 'Completed',
    location: 'Baltic Sea corridor',
  },
  {
    name: 'Baltic-1 Burial Campaign',
    campaignType: 'Burial',
    startDate: '2025-08-25',
    endDate: '2025-10-10',
    status: 'In Progress',
    location: 'Baltic Sea corridor',
  },
  {
    name: 'NorthLink Route Survey',
    campaignType: 'Route Survey',
    startDate: '2023-07-01',
    endDate: '2023-10-30',
    status: 'Completed',
    location: 'North Sea',
  },
  {
    name: 'NorthLink Cable A Installation',
    campaignType: 'Cable Installation',
    startDate: '2024-05-01',
    endDate: '2024-11-15',
    status: 'Completed',
    location: 'North Sea',
  },
  {
    name: 'NorthLink Testing & Commissioning',
    campaignType: 'Testing & Commissioning',
    startDate: '2025-01-15',
    endDate: '2025-03-01',
    status: 'In Progress',
    location: 'North Sea converter stations',
  },
  {
    name: 'Gulf Stream Pre-lay Survey',
    campaignType: 'Route Survey',
    startDate: '2023-02-01',
    endDate: '2023-05-30',
    status: 'Delayed',
    location: 'North Atlantic',
  },
  {
    name: 'Coral Sea Installation & Burial',
    campaignType: 'Burial',
    startDate: '2023-09-01',
    endDate: '2024-02-28',
    status: 'Completed',
    location: 'Coral Sea',
  },
];

export const tests = [
  {
    name: 'Baltic-1 FAT',
    testType: 'Factory Acceptance Test',
    standard: 'IEC 60840',
    result: 'Pass',
    testDate: '2025-02-10',
    engineer: 'Lukas Berg',
  },
  {
    name: 'Baltic-1 HV Withstand Test',
    testType: 'High Voltage Test',
    standard: 'IEC 62067',
    result: 'Pass',
    testDate: '2025-03-05',
    engineer: 'Lukas Berg',
  },
  {
    name: 'Baltic-2 FAT',
    testType: 'Factory Acceptance Test',
    standard: 'IEC 60840',
    result: 'Pending',
    testDate: '2026-01-15',
    engineer: 'Ingrid Nilsen',
  },
  {
    name: 'NorthLink Cable A FAT',
    testType: 'Factory Acceptance Test',
    standard: 'IEC 62067',
    result: 'Pass',
    testDate: '2024-02-20',
    engineer: 'Rachel Kim',
  },
  {
    name: 'NorthLink Cable A Mechanical Load Test',
    testType: 'Mechanical Load Test',
    standard: 'CIGRE TB 623',
    result: 'Pass',
    testDate: '2024-03-10',
    engineer: 'Rachel Kim',
  },
  {
    name: 'NorthLink Cable B FAT',
    testType: 'Factory Acceptance Test',
    standard: 'IEC 62067',
    result: 'Pass',
    testDate: '2024-09-01',
    engineer: 'Wei Tan',
  },
  {
    name: 'NorthLink Converter Station Commissioning Test',
    testType: 'Electrical Continuity Test',
    standard: 'IEC 61857',
    result: 'Pending',
    testDate: '2026-02-01',
    engineer: 'Rajesh Mehta',
  },
  {
    name: 'Emerald Backbone Prototype FAT',
    testType: 'Factory Acceptance Test',
    standard: 'ITU-T G.975',
    result: 'Pending',
    testDate: '2026-04-01',
    engineer: "Siobhan O'Brien",
  },
  {
    name: 'Gulf Stream Main Cable FAT',
    testType: 'Factory Acceptance Test',
    standard: 'IEC 62067',
    result: 'Fail',
    testDate: '2024-07-15',
    engineer: 'Marcus Alden',
  },
  {
    name: 'Gulf Stream Main Cable Retest',
    testType: 'Factory Acceptance Test',
    standard: 'IEC 62067',
    result: 'Pass',
    testDate: '2024-09-01',
    engineer: 'Marcus Alden',
  },
  {
    name: 'Coral Sea Export Cable Environmental Test',
    testType: 'Environmental Test',
    standard: 'IEC 60068',
    result: 'Pass',
    testDate: '2023-06-01',
    engineer: 'Amara Chen',
  },
  {
    name: 'Coral Sea Commissioning Continuity Test',
    testType: 'Electrical Continuity Test',
    standard: 'IEC 61857',
    result: 'Pass',
    testDate: '2024-05-20',
    engineer: 'Amara Chen',
  },
];

// Relationships reference nodes by their unique `name` property; the seed
// script resolves these to actual nodes at load time.
export const relationships = [
  // Project -> Cable
  { type: 'INCLUDES_CABLE', source: 'Baltic Wind Connector', target: 'Baltic-1 HVDC Cable' },
  { type: 'INCLUDES_CABLE', source: 'Baltic Wind Connector', target: 'Baltic-2 HVDC Cable' },
  { type: 'INCLUDES_CABLE', source: 'NorthLink HVDC Interconnector', target: 'NorthLink Interconnector Cable A' },
  { type: 'INCLUDES_CABLE', source: 'NorthLink HVDC Interconnector', target: 'NorthLink Interconnector Cable B' },
  { type: 'INCLUDES_CABLE', source: 'Emerald Isle Telecom Backbone', target: 'Emerald Backbone Fiber Trunk' },
  { type: 'INCLUDES_CABLE', source: 'Gulf Stream Power Bridge', target: 'Gulf Stream HVDC Main Cable' },
  { type: 'INCLUDES_CABLE', source: 'Coral Sea Renewable Export Cable', target: 'Coral Sea Export Cable' },

  // Project -> Campaign
  { type: 'INCLUDES_CAMPAIGN', source: 'Baltic Wind Connector', target: 'Baltic Route Survey 2024' },
  { type: 'INCLUDES_CAMPAIGN', source: 'Baltic Wind Connector', target: 'Baltic-1 Cable Installation' },
  { type: 'INCLUDES_CAMPAIGN', source: 'Baltic Wind Connector', target: 'Baltic-1 Burial Campaign' },
  { type: 'INCLUDES_CAMPAIGN', source: 'NorthLink HVDC Interconnector', target: 'NorthLink Route Survey' },
  { type: 'INCLUDES_CAMPAIGN', source: 'NorthLink HVDC Interconnector', target: 'NorthLink Cable A Installation' },
  { type: 'INCLUDES_CAMPAIGN', source: 'NorthLink HVDC Interconnector', target: 'NorthLink Testing & Commissioning' },
  { type: 'INCLUDES_CAMPAIGN', source: 'Gulf Stream Power Bridge', target: 'Gulf Stream Pre-lay Survey' },
  { type: 'INCLUDES_CAMPAIGN', source: 'Coral Sea Renewable Export Cable', target: 'Coral Sea Installation & Burial' },

  // Campaign -> Asset (the shared vessels/barges)
  { type: 'USES_ASSET', source: 'Baltic Route Survey 2024', target: 'MV Atlantic Surveyor', properties: { role: 'Survey vessel', allocationPercent: 100 } },
  { type: 'USES_ASSET', source: 'Baltic-1 Cable Installation', target: 'MV Nexus Installer', properties: { role: 'Cable lay', allocationPercent: 80 } },
  { type: 'USES_ASSET', source: 'Baltic-1 Cable Installation', target: 'Storage Barge Delta-7', properties: { role: 'Cable storage transfer', allocationPercent: 50 } },
  { type: 'USES_ASSET', source: 'Baltic-1 Burial Campaign', target: 'Trenchmaster Burial Vessel', properties: { role: 'Post-lay burial', allocationPercent: 100 } },
  { type: 'USES_ASSET', source: 'NorthLink Route Survey', target: 'MV Atlantic Surveyor', properties: { role: 'Route survey', allocationPercent: 100 } },
  { type: 'USES_ASSET', source: 'NorthLink Route Survey', target: 'ROV Deep Explorer', properties: { role: 'Seabed inspection', allocationPercent: 60 } },
  { type: 'USES_ASSET', source: 'NorthLink Cable A Installation', target: 'MV Nexus Installer', properties: { role: 'Cable lay', allocationPercent: 90 } },
  { type: 'USES_ASSET', source: 'NorthLink Cable A Installation', target: 'Storage Barge Delta-7', properties: { role: 'Cable storage transfer', allocationPercent: 70 } },
  { type: 'USES_ASSET', source: 'NorthLink Testing & Commissioning', target: 'ROV Deep Explorer', properties: { role: 'Subsea joint inspection', allocationPercent: 40 } },
  { type: 'USES_ASSET', source: 'Gulf Stream Pre-lay Survey', target: 'MV Atlantic Surveyor', properties: { role: 'Route survey', allocationPercent: 100 } },
  { type: 'USES_ASSET', source: 'Coral Sea Installation & Burial', target: 'Trenchmaster Burial Vessel', properties: { role: 'Burial', allocationPercent: 100 } },
  { type: 'USES_ASSET', source: 'Coral Sea Installation & Burial', target: 'Storage Barge Delta-7', properties: { role: 'Storage', allocationPercent: 30 } },

  // Project -> Asset (shared manufacturing plants + warehouse used by every project)
  { type: 'USES_ASSET', source: 'Baltic Wind Connector', target: 'Rotterdam Cable Manufacturing Plant', properties: { role: 'Cable manufacturing' } },
  { type: 'USES_ASSET', source: 'NorthLink HVDC Interconnector', target: 'Rotterdam Cable Manufacturing Plant', properties: { role: 'Cable manufacturing (Cable A)' } },
  { type: 'USES_ASSET', source: 'NorthLink HVDC Interconnector', target: 'Singapore Cable Factory', properties: { role: 'Cable manufacturing (Cable B)' } },
  { type: 'USES_ASSET', source: 'Emerald Isle Telecom Backbone', target: 'Singapore Cable Factory', properties: { role: 'Fiber cable manufacturing' } },
  { type: 'USES_ASSET', source: 'Gulf Stream Power Bridge', target: 'Rotterdam Cable Manufacturing Plant', properties: { role: 'Cable manufacturing' } },
  { type: 'USES_ASSET', source: 'Coral Sea Renewable Export Cable', target: 'Singapore Cable Factory', properties: { role: 'Cable manufacturing' } },
  { type: 'USES_ASSET', source: 'Baltic Wind Connector', target: 'North Sea Logistics Warehouse', properties: { role: 'Component & spares storage' } },
  { type: 'USES_ASSET', source: 'NorthLink HVDC Interconnector', target: 'North Sea Logistics Warehouse', properties: { role: 'Component & spares storage' } },
  { type: 'USES_ASSET', source: 'Emerald Isle Telecom Backbone', target: 'North Sea Logistics Warehouse', properties: { role: 'Component & spares storage' } },
  { type: 'USES_ASSET', source: 'Gulf Stream Power Bridge', target: 'North Sea Logistics Warehouse', properties: { role: 'Component & spares storage' } },
  { type: 'USES_ASSET', source: 'Coral Sea Renewable Export Cable', target: 'North Sea Logistics Warehouse', properties: { role: 'Component & spares storage' } },

  // Cable -> Test
  { type: 'TESTED_BY', source: 'Baltic-1 HVDC Cable', target: 'Baltic-1 FAT' },
  { type: 'TESTED_BY', source: 'Baltic-1 HVDC Cable', target: 'Baltic-1 HV Withstand Test' },
  { type: 'TESTED_BY', source: 'Baltic-2 HVDC Cable', target: 'Baltic-2 FAT' },
  { type: 'TESTED_BY', source: 'NorthLink Interconnector Cable A', target: 'NorthLink Cable A FAT' },
  { type: 'TESTED_BY', source: 'NorthLink Interconnector Cable A', target: 'NorthLink Cable A Mechanical Load Test' },
  { type: 'TESTED_BY', source: 'NorthLink Interconnector Cable B', target: 'NorthLink Cable B FAT' },
  { type: 'TESTED_BY', source: 'Emerald Backbone Fiber Trunk', target: 'Emerald Backbone Prototype FAT' },
  { type: 'TESTED_BY', source: 'Gulf Stream HVDC Main Cable', target: 'Gulf Stream Main Cable FAT' },
  { type: 'TESTED_BY', source: 'Gulf Stream HVDC Main Cable', target: 'Gulf Stream Main Cable Retest' },
  { type: 'TESTED_BY', source: 'Coral Sea Export Cable', target: 'Coral Sea Export Cable Environmental Test' },
  { type: 'TESTED_BY', source: 'Coral Sea Export Cable', target: 'Coral Sea Commissioning Continuity Test' },

  // Campaign -> Test
  { type: 'INCLUDES_TEST', source: 'NorthLink Testing & Commissioning', target: 'NorthLink Converter Station Commissioning Test' },
  { type: 'INCLUDES_TEST', source: 'Coral Sea Installation & Burial', target: 'Coral Sea Commissioning Continuity Test' },

  // Cable -> Campaign
  { type: 'INSTALLED_IN', source: 'Baltic-1 HVDC Cable', target: 'Baltic-1 Cable Installation' },
  { type: 'INSTALLED_IN', source: 'Baltic-1 HVDC Cable', target: 'Baltic-1 Burial Campaign' },
  { type: 'INSTALLED_IN', source: 'NorthLink Interconnector Cable A', target: 'NorthLink Cable A Installation' },
  { type: 'INSTALLED_IN', source: 'Coral Sea Export Cable', target: 'Coral Sea Installation & Burial' },

  // Generic cross-entity dependencies
  { type: 'DEPENDS_ON', source: 'Baltic-1 Burial Campaign', target: 'Baltic-1 Cable Installation', properties: { reason: 'Cable must be laid before burial', criticality: 'Critical' } },
  { type: 'DEPENDS_ON', source: 'NorthLink Testing & Commissioning', target: 'NorthLink Cable A Installation', properties: { reason: 'Commissioning requires cable installed', criticality: 'High' } },
  { type: 'DEPENDS_ON', source: 'Coral Sea Installation & Burial', target: 'Coral Sea Export Cable Environmental Test', properties: { reason: 'Environmental qualification required prior to offshore installation', criticality: 'High' } },

  // Asset -> Asset
  { type: 'PART_OF', source: 'Storage Barge Delta-7', target: 'North Sea Logistics Warehouse', properties: { reason: 'Barge is based at and managed from this facility' } },
];
